<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Te923tool\Module'                        => __DIR__ . '/Module.php',
    'Te923tool\Controller\MainController' => __DIR__ . '/src/Te923tool/Controller/MainController.php',
    'Te923toolTest\Framework\TestCase'        => __DIR__ . '/tests/Te923tool/Framework/TestCase.php',
    'Te923toolTest\SampleTest'                => __DIR__ . '/tests/Te923tool/SampleTest.php',
);
