<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                        => __DIR__ . '/Module.php',
    'Application\Controller\ConsoleController' => __DIR__ . '/src/Application/Controller/ConsoleController.php',
    'ApplicationTest\Framework\TestCase'        => __DIR__ . '/tests/Application/Framework/TestCase.php',
    'ApplicationTest\SampleTest'                => __DIR__ . '/tests/Application/SampleTest.php',
);
